# ch5-ex
setwd("D:\\undergraduate\\研\\432统计学\\应用时间序列分析资料\\R解答")
library(openxlsx)
library(tseries)
library(aTSA)
library(forecast)

## ex1
rm(list=ls(all=TRUE))
E5_1 <- read.xlsx(".\\datafile\\E5_1.xlsx", sheet=1)
x <- ts(E5_1$volume, start=1949)
par(mfrow=c(1,2))
plot(x)
plot(diff(x))
adf.test(diff(x))
Box.test(diff(x))
par(mfrow=c(1,2))
acf(diff(x))
pacf(diff(x))
fit <- Arima(x, order=c(1,1,0), include.drift=T)
tsdiag(fit)
fore <- forecast(fit, h=5)
par(mfrow=c(1,1))
plot(fore)
lines(fore$fitted, col=2)

## ex2
rm(list=ls(all=TRUE))
E5_2 <- read.xlsx(".\\datafile\\E5_2.xlsx", sheet=1)
x <- ts(E5_2$birth_rate, start=1750)
plot(x)
adf.test(x)
Box.test(x)
par(mfrow=c(1,2))
acf(x)
pacf(x)
fit <- arima(x, order=c(1,0,0))

## ex3
rm(list=ls(all=TRUE))
E5_3 <- read.xlsx(".\\datafile\\E5_3.xlsx", sheet=1)
x <- ts(E5_3$number, start=1867)
par(mfrow=c(1,2))
plot(x)
plot(diff(x))
adf.test(diff(x))
Box.test(diff(x))
par(mfrow=c(1,2))
acf(diff(x))
pacf(diff(x))
fit1 <- Arima(x,order=c(3,1,0), include.drift=T); fit1
fit2 <- arima(x,order=c(3,1,0), transform.pars=F, fixed=c(NA,0,NA)); fit2
tsdiag(fit2)
fore <- forecast(fit2, h=7)
par(mfrow=c(1,1))
plot(fore)
lines(fore$fitted, col=2)

## ex4
rm(list=ls(all=TRUE))
E5_4 <- read.xlsx(".\\datafile\\E5_4.xlsx", sheet=1)
x1 <- ts(E5_4$birth_rate, start=1980)
x2 <- ts(E5_4$mortality, start=1980)
x3 <- ts(E5_4$ngr, start=1980)
### birth_rate
par(mfrow=c(1,2))
plot(x1)
plot(diff(x1))
adf.test(diff(x1))
for(i in 1:6) print(Box.test(diff(x1), i))
par(mfrow=c(1,2))
acf(diff(x1))
pacf(diff(x1))
fit11 <- arima(x1, order=c(0,1,0))
fit12 <- arima(x1, order=c(0,1,1))
fit13 <- arima(x1, order=c(1,1,0))
c(AIC(fit11), AIC(fit12), AIC(fit13), BIC(fit11), BIC(fit12), BIC(fit13))
fit12
fore1 <- forecast(fit12, h=10); fore1
### mortality
par(mfrow=c(1,2))
plot(x2)
plot(diff(x2))
adf.test(diff(x2))
for(i in 1:6) print(Box.test(diff(x2), i))
par(mfrow=c(1,2))
acf(diff(x2))
pacf(diff(x2))
fit21 <- arima(x2, order=c(0,1,0))
fit22 <- arima(x2, order=c(0,1,1))
fit23 <- arima(x2, order=c(1,1,0))
c(AIC(fit21), AIC(fit22), AIC(fit23), BIC(fit21), BIC(fit22), BIC(fit23))
fit21
fore2 <- forecast(fit21, h=10); fore2
### ngr
par(mfrow=c(1,2))
plot(x3)
plot(diff(x3))
adf.test(diff(x3))
for(i in 1:6) print(Box.test(diff(x3), i))
par(mfrow=c(1,2))
acf(diff(x3))
pacf(diff(x3))
fit31 <- arima(x3, order=c(0,1,0))
fit32 <- arima(x3, order=c(0,1,1))
fit33 <- arima(x3, order=c(1,1,0))
c(AIC(fit31), AIC(fit32), AIC(fit33), BIC(fit31), BIC(fit32), BIC(fit33)) 
fit32
fore3 <-forecast(fit32, h=10); fore3

## ex5
rm(list=ls(all=TRUE))
E5_5 <- read.xlsx(".\\datafile\\E5_5.xlsx", sheet=1)
x1 <- ts(E5_5$maize_price, start=1867)
x2 <- ts(E5_5$maize_yield, start=1867)
x3 <- ts(E5_5$wages, start=1867)
x4 <- ts(E5_5$pig_price, start=1867)
x5 <- ts(E5_5$pig_yield, start=1867)
### maize_price
par(mfrow=c(1,2))
plot(x1)
plot(diff(x1))
adf.test(diff(x1))
for(i in 1:6) print(Box.test(diff(x1), i))
par(mfrow=c(1,2))
acf(diff(x1))
pacf(diff(x1))
fit1 <- arima(x1, order=c(0,1,7), transform.pars=F, fixed=c(0,0,0,0,0,0,NA))
fore1 <- forecast(fit1, h=10); fore1
par(mfrow=c(1,1))
plot(fore1)
lines(fore1$fitted, col=2)
### maize_yield
par(mfrow=c(1,2))
plot(x2)
plot(diff(x2))
adf.test(diff(x2))
for(i in 1:6) print(Box.test(diff(x2), i))
par(mfrow=c(1,2))
acf(diff(x2))
pacf(diff(x2))
fit2 <- Arima(x2, order=c(0,1,1), include.drift=T)
fore2 <- forecast(fit2, h=10); fore2
par(mfrow=c(1,1))
plot(fore2)
lines(fore2$fitted, col=2)
### wages
par(mfrow=c(1,2))
plot(x3)
plot(diff(x3))
adf.test(diff(x3))
for(i in 1:6) print(Box.test(diff(x3), i))
par(mfrow=c(1,2))
acf(diff(x3))
pacf(diff(x3))
fit3 <- arima(x3, order=c(13,1,0), transform.pars=F, fixed=c(NA,0,0,0,0,0,0,0,0,0,0,0,NA))
fore3 <-forecast(fit3, h=10); fore3
par(mfrow=c(1,1))
plot(fore3)
lines(fore3$fitted, col=2)
### pig_price
par(mfrow=c(1,2))
plot(x4)
plot(diff(x4))
adf.test(diff(x4))
for(i in 1:6) print(Box.test(diff(x4), i))
par(mfrow=c(1,2))
acf(diff(x4))
pacf(diff(x4))
fit4 <- arima(x4, order=c(3,1,0))
fore4 <-forecast(fit4, h=10); fore4
par(mfrow=c(1,1))
plot(fore4)
lines(fore4$fitted, col=2)
### pig_yield
par(mfrow=c(1,2))
plot(x5)
plot(diff(x5))
adf.test(diff(x5))
for(i in 1:6) print(Box.test(diff(x5), i))
par(mfrow=c(1,2))
acf(diff(x5))
pacf(diff(x5))
fit5 <- arima(x5, order=c(5,1,0), transform.pars=F, fixed=c(0,NA,NA,0,NA))
fore5 <-forecast(fit5, h=10); fore5
par(mfrow=c(1,1))
plot(fore5)
lines(fore5$fitted, col=2)

